name: Black

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - name: "check_black"
        run: |
          pip install black
          base_ref=origin/${{ github.base_ref }}
          filelist=$(git diff --name-only --diff-filter=d $base_ref | grep -e="*.py$")
          echo "$filelist"
          black --check --diff -- "$filelist"
