name: Check DVC

on: pull_request

jobs:
  dvcchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - name: "dvc_filelist"
        # Get new and modified DVC files:
        run: |
          base_ref=origin/${{ github.base_ref }}
          filelist=$(git diff --name-only --diff-filter=d $base_ref | sed -n "/\.dvc$/ p")
          echo "New and modified DVC files: $filelist"
          echo "::set-env name=filelist::$filelist"
      - name: "install dvc"
        run: |
          pip install dvc[all]
      - name: "check dvc data"
        # Check if DVC data is pushed to remote
        run: |
          if [ -z "$filelist" ]; then
            echo "There are no changed DVC files"
            exit
          fi

          SSH_DIR="$HOME/.ssh"

          echo "Creating dir $SSH_DIR..."
          mkdir "$SSH_DIR"

          keyfile="$SSH_DIR/dvc_rsa"
          touch "$keyfile"
          echo "${{ secrets.DVCREPO_RSA }}" > "$keyfile"
          # Keep md5sum in logs te ensure key is correct:
          md5sum "$keyfile"

          CONFIG_FILE="$SSH_DIR/config"
          echo "Creating config file $CONFIG_FILE"
          touch "$CONFIG_FILE"
          echo "Host 206.189.188.13" > "$CONFIG_FILE"
          # define any custom port you want:
          # echo "    Port custom_port" >> "$CONFIG_FILE"
          echo "    User dvcrepo" >> "$CONFIG_FILE"
          echo "    IdentityFile $keyfile" >> "$CONFIG_FILE"

          dvc_status=$(dvc status --cloud --show-json "$filelist")
          # Log dvc status:
          echo "$dvc_status"
          # Filter 'missing' files, i.e. files not pushed to remote:
          missing=$(echo "$dvc_status" | python -c 'import sys; import json; missing = {k: v for k, v in json.load(sys.stdin).items() if v == "missing"}; print(json.dumps(missing, ensure_ascii=False, indent=4) if missing else "")')
          if [[ -n "$missing" ]]; then
            echo "Not all dvc files synced with remote:"
            echo "$missing"
            exit 1
          fi
