name: my-conda-env

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: my-conda-env
        environment-file: conda-env.yml
        # python-version: 3.10
        auto-activate-base: false
    - name: Check environment
      run: |
        conda info
        conda env list
