name: Python Linters

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - name: "black"
        run: |
          filelist=$(git diff --name-only --diff-filter=d $base_ref | grep -e="*.py$")
          if [[ -n "$filelist" ]]; then
            pip install black
            black --check --diff -- "$filelist"
          fi
      - name: "flake8"
        run: |
          filelist=$(git diff --name-only --diff-filter=d $base_ref | grep -e="*.py$")
          if [[ -n "$filelist" ]]; then
            pip install flake8
            flake8 --count --select=E9,F63,F7,F82 --show-source --statistics -- "$filelist"
          fi

